#ifndef _DEFAULTS_H_
#define _DEFAULTS_H_

#define BLOCK_SIZE 40

#define FIELD_WIDTH 20
#define FIELD_HEIGHT 15

#define WINDOW_WIDTH (FIELD_WIDTH * BLOCK_SIZE)
#define WINDOW_HEIGHT (FIELD_HEIGHT * BLOCK_SIZE)

#define SNAKE_SIZE 15
#define SNAKE_START_X SNAKE_SIZE
#define SNAKE_START_Y (FIELD_HEIGHT / 2)

#endif /* _DEFAULTS_H_ */

